"use client";

import { useEffect, useRef, useState } from "react";
import { useMutation, useQuery } from "@tanstack/react-query";
import { toast } from "sonner";
import { Send } from "lucide-react";

import { api } from "@/lib/api";
import { Badge } from "@/components/ui/badge";
import { Button } from "@/components/ui/button";
import { Card, CardContent } from "@/components/ui/card";
import { Skeleton } from "@/components/ui/skeleton";
import { PageHeader } from "@/components/PageHeader";
import { SectionHeader } from "@/components/SectionHeader";
import { ErrorCard } from "@/components/ErrorCard";
import { SegmentCard } from "@/components/SegmentCard";

const SAMPLE_QUESTIONS = [
  "Why is Q1 revenue down?",
  "Which patient segments are highest value?",
  "Who should we prioritize for recall this week?",
  "Which marketing channel should I cut first?",
  "Which service categories are growing?",
  "How do I build a custom chart?",
];

function TypewriterAnswer({ text }: { text: string }) {
  const [shown, setShown] = useState("");
  useEffect(() => {
    setShown("");
    let i = 0;
    const id = setInterval(() => {
      i += 1;
      setShown(text.slice(0, i));
      if (i >= text.length) clearInterval(id);
    }, 18);
    return () => clearInterval(id);
  }, [text]);
  return (
    <div className="flex justify-start">
      <div className="max-w-[85%] rounded-2xl rounded-bl-sm bg-muted px-4 py-2 text-sm leading-relaxed duration-200 animate-in fade-in slide-in-from-left-2">
        {shown}
        {shown.length < text.length && (
          <span className="ml-0.5 inline-block h-3.5 w-1.5 animate-pulse bg-primary align-text-bottom" />
        )}
      </div>
    </div>
  );
}

export default function AiStudioPage() {
  const segments = useQuery({ queryKey: ["segments"], queryFn: api.getSegments });

  const [input, setInput] = useState("");
  const [asked, setAsked] = useState<string | null>(null);
  const scrollRef = useRef<HTMLDivElement>(null);

  const chat = useMutation({
    mutationFn: (q: string) => api.askChat(q),
    onError: () =>
      toast.error("Couldn't reach the assistant — is the API running?"),
  });

  function ask(question: string) {
    const q = question.trim();
    if (!q || chat.isPending) return;
    setAsked(q);
    setInput("");
    chat.mutate(q);
  }

  useEffect(() => {
    scrollRef.current?.scrollIntoView({ behavior: "smooth", block: "end" });
  }, [chat.data, chat.isPending]);

  return (
    <div className="space-y-8">
      <PageHeader title="AI Studio" subtitle="Segments and answers from your practice data" />

      {/* Section A — real ML segments */}
      <div className="space-y-4">
        <div className="flex flex-wrap items-baseline justify-between gap-2">
          <SectionHeader title="Patient segments discovered from your data" />
          <p className="text-sm text-muted-foreground">
            Unsupervised k-means across 12 behavior features.{" "}
            <Badge
              variant="secondary"
              title="The k-means model is re-fit every Monday at 3am by an Airflow DAG, so segments always reflect the latest patient behavior."
              className="cursor-help align-middle"
            >
              Retrained weekly
            </Badge>{" "}
            via Airflow.
          </p>
        </div>

        {segments.isError ? (
          <ErrorCard message="Couldn't load segments." onRetry={() => segments.refetch()} />
        ) : segments.isLoading ? (
          <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">
            {Array.from({ length: 6 }).map((_, i) => (
              <Card key={i}>
                <CardContent className="space-y-3 p-5">
                  <Skeleton className="h-4 w-40" />
                  <Skeleton className="h-8 w-20" />
                  <Skeleton className="h-4 w-full" />
                </CardContent>
              </Card>
            ))}
          </div>
        ) : (
          <div className="grid gap-4 sm:grid-cols-2 xl:grid-cols-3 2xl:grid-cols-4">
            {(segments.data ?? []).map((s) => (
              <SegmentCard key={s.cluster_id} segment={s} />
            ))}
          </div>
        )}
      </div>

      {/* Section B — live RAG chat */}
      <div className="space-y-4">
        <div className="flex flex-wrap items-center justify-between gap-2">
          <SectionHeader title="Ask about your practice" />
          <Badge
            variant="secondary"
            title="Answers are generated by Claude, grounded only in a retrieved knowledge base built from your marts (revenue, providers, segments, recall, channels, service mix). Retrieval-augmented generation — no free-form guessing."
            className="cursor-help align-middle"
          >
            Level 1 · retrieval-grounded
          </Badge>
        </div>

        <Card>
          <CardContent className="space-y-4 p-5">
            <div className="flex flex-wrap gap-2">
              {SAMPLE_QUESTIONS.map((q) => (
                <button
                  key={q}
                  type="button"
                  disabled={chat.isPending}
                  onClick={() => ask(q)}
                  className="rounded-full border border-border bg-muted/40 px-3 py-1.5 text-xs text-muted-foreground transition hover:bg-muted disabled:cursor-not-allowed disabled:opacity-50"
                >
                  {q}
                </button>
              ))}
            </div>

            {asked && (
              <div className="space-y-2 border-t border-border pt-4">
                <div className="flex justify-end">
                  <div className="max-w-[80%] rounded-2xl rounded-br-sm bg-primary px-4 py-2 text-sm text-primary-foreground">
                    {asked}
                  </div>
                </div>

                {chat.isPending ? (
                  <div className="flex justify-start">
                    <div className="flex items-center gap-1.5 rounded-2xl rounded-bl-sm bg-muted px-4 py-3 text-sm text-muted-foreground">
                      <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-current [animation-delay:-0.2s]" />
                      <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-current [animation-delay:-0.1s]" />
                      <span className="h-1.5 w-1.5 animate-bounce rounded-full bg-current" />
                    </div>
                  </div>
                ) : chat.isError ? (
                  <p className="text-sm text-muted-foreground">
                    Something went wrong. Try again.
                  </p>
                ) : chat.data ? (
                  <div className="space-y-2">
                    <TypewriterAnswer key={asked} text={chat.data.answer} />
                    {chat.data.sources.length > 0 && (
                      <p className="pl-1 text-xs text-muted-foreground">
                        Based on:{" "}
                        {chat.data.sources.map((s) => s.title).join(" · ")}
                      </p>
                    )}
                  </div>
                ) : null}
                <div ref={scrollRef} />
              </div>
            )}

            <form
              onSubmit={(e) => {
                e.preventDefault();
                ask(input);
              }}
              className="flex items-center gap-2 pt-1"
            >
              <input
                value={input}
                onChange={(e) => setInput(e.target.value)}
                disabled={chat.isPending}
                placeholder="Ask a question about revenue, providers, segments, recall…"
                className="w-full rounded-lg border border-border bg-background px-4 py-2 text-sm outline-none transition focus:border-primary disabled:opacity-50"
              />
              <Button type="submit" size="sm" disabled={chat.isPending || !input.trim()}>
                <Send className="h-3.5 w-3.5" />
                Ask
              </Button>
            </form>
          </CardContent>
        </Card>
      </div>
    </div>
  );
}
